version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASA_NAME}
      - MYSQL_USER=${DATABASE_NAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork
    ports:
      - "3306:3306"

networks:
  mynetwork:

volumes:
  mariadb_data: