version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    entrypoint: >
      sh -c "npm run dev"
    networks:
      - mynetwork
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASA_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork
    ports:
      - "3306:3306"

networks:
  mynetwork:

volumes:
  mariadb_data: