name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client
    
    - name: Add SSH key
      run: |
        echo "${{ secrets.AWS_EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem
        eval $(`ssh-agent -s`)
        ssh-add key.pem

    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Deploy to Server
      env:
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        WEB_HOST: ${{ secrets.WEB_HOST }}
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-54-226-30-217.compute-1.amazonaws.com <<EOF
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker pull robe/development:condo-app
          docker stop condo-app || true
          docker rm condo-app || true
          docker run -d --name condo-app \  
            -e DATABASE_USER=$DATABASE_USER \
            -e DATABASE_PASSWORD=$DATABASE_PASSWORD \
            -e DATABASE_NAME=$DATABASE_NAME \
            -e DATABASE_HOST=$DATABASE_HOST \
            -e DATABASE_PORT=$DATABASE_PORT \
            -e DATABASE_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_REGION=$AWS_REGION \
            -e AWS_BUCKET_NAME=$AWS_BUCKET_NAME \
            -e WEB_HOST=$WEB_HOST \
            -e MAILGUN_API_KEY=$MAILGUN_API_KEY \
            -e MAILGUN_DOMAIN=$MAILGUN_DOMAIN \
            -e JWT_SECRET=$JWT_SECRET \
            -p 80:80 robe/development:condo-app\
            docker exec condo-app npx knex migrate:latest --knexfile db/knex.ts

        EOF
