name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t condo-app .

      - name: Push Docker image to Docker Hub
        run: docker push condo-app

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.SERVER_USERNAME}}@${{ secrets.SERVER_PASSWORD }} 'docker pull robe/development:condo-app && docker stop condo-app || true && docker rm condo-app || true && docker run -d -p 3000:3000 --name condo-app condo-app'
